### ISSUE TITLE
관리자 메뉴에서 게시판 추가 시 에러 발생

### ISSUE THREAD

**Issue by hellodhlyn** [TintypeMolly/Yuzuki#103]
관리자 메뉴에서 게시판 생성 버튼을 누르면 INTERNAL SERVER ERROR가 발생함.

**Comment by Perlmint** [comment]
???? https://github.com/PoolC/Yuzuki/blob/master/resource/admin.py#L117 코드가 없음 ?????

**Comment by hellodhlyn** [comment]
??? 원래 없던건가요 아니면 잘 있던 코드가 집나간건가요

**Comment by Perlmint** [comment]
blame걸어보니 원래 없던걸로...

**Comment by Perlmint** [comment]
그리고 self-assign...

**Comment by Perlmint** [comment]
@HelloDHLyn 실 서버에 적용, 테스트 후 close please

**Comment by hellodhlyn** [comment]
Checked
