### ISSUE TITLE
게시글 본문 이미지 크기 설정

### ISSUE THREAD

**Issue by hellodhlyn** [TintypeMolly/Yuzuki#109]
게시글 본문의 이미지에 max-width가 지정이 되어있지 않아 큰 크기의 그림을 첨부할 경우 화면 밖으로 탈출.

**Comment by Perlmint** [comment]
실 서버에 적용 안되어 있음. 적용 및 확인 후 close 처리 필요

**Comment by hellodhlyn** [comment]
Deployed
