### ISSUE TITLE
굴러다니는 ssl certificate 하나 있는데

### ISSUE THREAD

**Issue by scarlet9** [TintypeMolly/Yuzuki#17]
드리면 붙여주나요?

아님 어차피 nginx라면 설정하게 권한좀 굽신굽신.

**Comment by TintypeMolly** [comment]
엥? SSL Cert 그거 도메인 종속적인거 아니었던가? 나도 해본지 오래되서 기억 잘 안나긴 하는데... 일단 백엔드 앞단은 nginx고 proxy pass하고있는거라 붙이면 붙일 순 있을거임. 내일 발표 끝나고 한번 봅시다 ㅇㅇ.
