### ISSUE TITLE
[채팅] 멘션 자동완성

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#20]
멘션 자동완성 넣어주세요!

페이스북 웹에서 포스트에 멘션 달때 같은 디자인으로

**Comment by TintypeMolly** [comment]
`<input type="text">` 에서 @ 입력하면 suggestion 창 띄우는 gist 하나만 던져주셈. 쉬우면 내가 넣고. ajax는 당연히 안써도 되고 dummy 닉네임 10개쯤 만들어서 보내줘

**Comment by angdev** [comment]
제가 해도 되겠습니까- 이미 작업하고 계신가 해서요

**Comment by TintypeMolly** [comment]
안하고있음. 하셈.

**Comment by TintypeMolly** [comment]
자동완성 대상은 전체회원으로!

**Comment by angdev** [comment]
채팅방 접속 인원 중에서만 하는게 아니라 동아리 전체 인원이 대상이라는 말씀이신가요?

**Comment by TintypeMolly** [comment]
Yeap
