### ISSUE TITLE
[게시판] 게시판 문법 도움말

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#22]
확장기능도 있으니 문법 도움말 좀

**Comment by Perlmint** [comment]
https://poolc.org/article/view?id=372&page=1 대충 쓰다 만 것... 좀 더 정리하면 될 것 같은데

**Comment by Perlmint** [comment]
#88 이 완성되면 사용해서 작성하면 될 듯.

도움말 자체는 앞서 작성한 코멘트에 있는 글의 내용으로 사용

**Comment by TintypeMolly** [comment]
added 3adba2c73cba4e12c54c81e01dcb0c7975fd8942
