### ISSUE TITLE
[게시판]  텍스트 에디터

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#24]
간단하게라도 마크다운 하이라이팅이 되는 에디터를 사용할 수 있도록 제공

**Comment by Perlmint** [comment]
http://codemirror.net/ 를 사용하면 좋을 것 같음

**Comment by angdev** [comment]
assigned to @Perlmint ?

**Comment by Perlmint** [comment]
하는김에 템플릿도 공통 부분 정리

**Comment by angdev** [comment]
:+1:

**Comment by TintypeMolly** [comment]
done bcbfa5183299ea28e40a69abec54e515ea414b4e
