### ISSUE TITLE
 버그 리포트 게시판을 제거하고 깃헙 이슈로 연결

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#25]
이슈트래커에 사람들이 익숙해질 수 있도록 게시판을 아예 제거하고 깃헙 이슈페이지로 연결하기

혹은 github api를 사용해서 이슈를 볼 수 있게 해주고 간단한 도움말을 같이 보여주기

**Comment by angdev** [comment]
버그 게시판 링크를 이 쪽으로 연결하는 것에 한 표를 던져봅니다.
동아리 홈페이지 오른쪽 위 귀퉁이에 fork me 리본 달아놓으면 웃길 것 같군요 =3

**Comment by TintypeMolly** [comment]
근데 지금 열려있는 게시판을 닫는 기능이 존재하지 않음. 컬럼 추가해야될듯

**Comment by TintypeMolly** [comment]
일단 버그게시판은 닫았다

**Comment by TintypeMolly** [comment]
fork 리본이 뭔지 설명 부탁 @FeGs

**Comment by angdev** [comment]
@TintypeMolly https://github.com/blog/273-github-ribbons

**Comment by Perlmint** [comment]
포크리본은 재미는 있지만 좀 아니라고 생각함

**Comment by TintypeMolly** [comment]
메인페이지에 붙일 생각임. 그리고 버그리포트는 왼쪽 메뉴바 맨 아래쪽에 쪼만하게 달 생각이다.

**Comment by TintypeMolly** [comment]
아니다. 좀 뜬금없네. 둘다 메뉴바 왼쪽 아래 달아버릴까. 하여간 실제로 달아보고 고민좀 하겠음

**Comment by TintypeMolly** [comment]
done 89d6fdd668b493563cd5cc8898451336e708806a
