### ISSUE TITLE
새 글 보기에서 내용이 길면 잘라서 보여주기

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#37]
![2015-03-13 1 04 17](https://cloud.githubusercontent.com/assets/1954350/6632897/7d951e2a-c981-11e4-99f7-7b74411c2da9.png)

여기서 내용 부분을 적절히 잘라서 `어쩌고 저쩌고...` 이렇게 보여주는게 좋을 것 같아요.

**Comment by TintypeMolly** [comment]
콜
