### ISSUE TITLE
채팅에서 이전에 보냈던 메시지를 다시 찾아 보낼 수 있는 기능

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#40]
방향키 위로 누르면 이전에 보냈던 메시지가 나오면 가끔은 편하겠지요.

**Comment by TintypeMolly** [comment]
/로 시작하는 메시지를 입력하는 실수를 했을 때 특별히 편하겠지.

**Comment by TintypeMolly** [comment]
클라이언트 사이드 구현해야 할듯. 이전메시지 한계 한 20개정도로 해주고

**Comment by TintypeMolly** [comment]
done 27c87de
