### ISSUE TITLE
No Such Child not covered

### ISSUE THREAD

**Issue by TintypeMolly** [TintypeMolly/Yuzuki#43]
https://poolc.org/chat/asd

Doesn't show pretty illya chan

Must override `YuzukiResource.getChild`(`getChildWithDefault` maybe) behaviour

**Comment by TintypeMolly** [comment]
![illya](https://cloud.githubusercontent.com/assets/2056635/6643674/819e681c-c9f1-11e4-9942-6c9f9df2951a.jpg)
So critical

**Comment by angdev** [comment]
Go to sleep
