### ISSUE TITLE
글 삭제할 때 confirm 요청하기

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#44]
지금은 바로 success alert가 뜨는데 한 번 물어보는게 좋을 것 같습니다. 메시지도 변경하는게 좋을듯 하군요.

**Comment by TintypeMolly** [comment]
슈ㅣ발 방금 당했다. 삭제하고 싶지 않았는데 바로 삭제당했어

**Comment by TintypeMolly** [comment]
fixed b0cd72cd2c7d37971e955896fbf729466a3c238b
