### ISSUE TITLE
게시판 이동 시 왼쪽 메뉴 상태 유지

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#49]
정확하게는 유지라기보다는 보고 있는 게시판이 왼쪽 메뉴에서 가려져있는 것을 피하면 좋겠음

url을 보고 스크롤을 조금 해주던가 해야할 듯 싶음

**Comment by TintypeMolly** [comment]
? 상세 설명 부탁. 이해가 안됨. 보고있는 게시판은 지금도 active로 해놓을텐데?

**Comment by TintypeMolly** [comment]
왼쪽 메뉴의 스크롤 상태를 유지하고 싶다는 건데, 이거 위치 기억하려면 iframe 써야되는 등 뭔가 귀찮을듯.

**Comment by TintypeMolly** [comment]
이거 일단 닫겠음.
