### ISSUE TITLE
채팅 페이지네이션보다 스트림에 더 어울리는 UX개발

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#50]
스트림이기 때문에 페이지로 구분하는게 잘 어울리지 않는 것 같다.

ajax를 사용해서 이전 대화 가져오기를 구현하고
각 대화의 id를 fragment id를 활용해서 참조하는 방식을 쓰는 것이 좋을 것 같음.

fragment id를 사용하면 해당 대화의 link를 생성할 수 있도록 컨텍스트 메뉴도 작성이 필요함

**Comment by TintypeMolly** [comment]
fragment 개념에 대한 상세한 제안 부탁.
1. UX에 대한 것은 적절하다면 변경할 생각은 있지만( @FeGs 가 제안한다고 예고했었음) #32 
2. chat을 permlink로 만들어서 공유할만한 필요가 있는가에 대한 것은 의문이 있는데
그렇게 할만한 이유가 존재하는지?
그리고 만약 존재한다면 fragment를 사용해서 링크하는 예시 시나리오를 제시하시오.

**Comment by TintypeMolly** [comment]
fragment가 http://example.com/page#foo 에서 foo같은거 말하는 거였군

**Comment by angdev** [comment]
일단 proposal은 여러 개 나와도 상관없으니 다른 사람의 제안도 받아보죠.

**Comment by TintypeMolly** [comment]
@FeGs 음 제안을 어떻게 받지?

**Comment by Perlmint** [comment]
채팅방 사용 안하므로 닫음
