### ISSUE TITLE
버그리포트 -> 버그리포트/기능 제안 으로 변경

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#53]
기능 제안도 받고 있으니 텍스트를 단순 버그 리포트만으로 하는 것보다는 바꾸는 것이 좋을 것 같음

**Comment by TintypeMolly** [comment]
좁아서 힘들 것 같은데. 다른이름 제안좀.

**Comment by Perlmint** [comment]
Issue report하면 간단하고 참 좋겠지만... 일단 그냥 몇개 던져보면
1. 버그 / 새 기능
2. Issue report
3. 사이트 개선

딱히 좋은 이름이 생각 안나네...

**Comment by angdev** [comment]
저도 굳이 안 떠오르긴 하는데 3번? 혹은 그냥 2번을 한글로 이슈 리포트?

**Comment by TintypeMolly** [comment]
사이트 개선쪽이 좋은듯? 풀리퀘 넣으셈 @Perlmint

**Comment by TintypeMolly** [comment]
그냥 내가하겠음 @Perlmint

**Comment by TintypeMolly** [comment]
done 4f459a331de2cc9a82b2b70976d3ecba85d5c942
