### ISSUE TITLE
댓글 수정 기능 수정 요청

### ISSUE THREAD

**Issue by todd032** [TintypeMolly/Yuzuki#55]
여기에 적어도 되는건가...?

어쩃든 현재 게시글 댓글 수정시 "사라진 댓글입니다" 가 출력되는 오류가 발생.

따라서 다음과 같은 흐름으로 기능을 수정해줬으면 함.

댓글 수정 버튼 클릭 - > 입력 칸에 기존에 적은 텍스트가 들어가 있는 상태로 표시 -> 사용자는 해당 텍스트들을 수정 -> 수정 확인 버튼 클릭 -> 기존 댓글 수정 완료.

**Comment by TintypeMolly** [comment]
fixed d9c5a32d096eba8dadc00d4f5f8e08f983136cbe

**Comment by angdev** [comment]
수정 누르면 기존 텍스트가 input box에 남아있는 기능 구현은 없나요?

**Comment by TintypeMolly** [comment]
아 기존텍스트 유지도 해야되나?

**Comment by TintypeMolly** [comment]
지금 상태가 article_view.html을 다시 짜야될 수준인 것 같다. 일단은 기능만 만들어서 올리고 디자인좀 손봐야될듯...

**Comment by TintypeMolly** [comment]
fixed 8a966f27cdaa477af69bc57e1725717be461438d

**Comment by angdev** [comment]
:+1:
