### ISSUE TITLE
채팅 커넥션이 끊겼을 때 자동으로 연결 복구를 해주기

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#56]
노트북 닫았다가 다시 열었을 때 새로고침해야해서 짜증나요

**Comment by TintypeMolly** [comment]
방법이 있나?

**Comment by skyser2003** [comment]
일단 미봉책으로 끊기면 자동으로 새로고침..?

**Comment by TintypeMolly** [comment]
현재 pending중인 http req를 받아온다던가 하는 게 없으면 딱히 알 방법을 모르겠다는거. 그런게 있었나?

**Comment by Perlmint** [comment]
채팅방 사용 안하므로 닫음
