### ISSUE TITLE
맨 처음 실행 시 log 폴더 없으면 실행이 안 되는 문제

### ISSUE THREAD

**Issue by skyser2003** [TintypeMolly/Yuzuki#60]
해결 : log 폴더가 없으면 만들어주자

**Comment by Perlmint** [comment]
@skyser2003 해결책도 명확하니 풀리퀘 기대하겠음

**Comment by angdev** [comment]
@skyser2003 :+1:

**Comment by TintypeMolly** [comment]
@skyser2003 :+1:

**Comment by TintypeMolly** [comment]
added 4ddec0e31d41f3a946329e9fcfbdd29627eeaccb

**Comment by Perlmint** [comment]
@skyser2003 실망...

**Comment by angdev** [comment]
@skyser2003 실망...

2015년 4월 6일 월요일, Gyusun Yeomnotifications@github.com님이 작성한 메시지:

> @skyser2003 https://github.com/skyser2003 실망...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TintypeMolly/Yuzuki/issues/60#issuecomment-90071561.

## 

연세대학교 컴퓨터과학과 3학년 홍철주
010 6701 2676 | ang0123dev@gmail.com

**Comment by TintypeMolly** [comment]
@skyser2003 실망했다
