### ISSUE TITLE
멘션 자동완성 대소문자 가리지 않도록 하기

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#61]
닉네임 첫 글자가 대문자 이신 분 멘션하기가 힘들군요. (Zeclix 라던가 Zeclix 같은 분이요)
case insensitive로 검색하게 하는 기능을 넣고자 하는데 어떠신가요?

**Comment by Perlmint** [comment]
+1 thumb up

**Comment by TintypeMolly** [comment]
:+1:

**Comment by TintypeMolly** [comment]
added 653a736be319362751e50d5147f04eedf29b49af
