### ISSUE TITLE
멘션 자동완성에 한글 초중종성 분리 해서 처리하기

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#62]
match정규식과 search필터만 변경하면 됨

참고: http://byuli.tistory.com/entry/javascript-%EB%A1%9C-%EA%B5%AC%ED%98%84%ED%95%9C-%ED%95%9C%EA%B8%80-%EC%9E%90%EC%86%8C-%EB%B6%84%EB%A6%AC

**Comment by TintypeMolly** [comment]
added a08fcdfcd41ae646dd376dc3fede5432cfb677dd
