### ISSUE TITLE
특정 글의 각주가 다른 글에서도 보이는 문제

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#66]
https://poolc.org/article/view?id=175&page=1 의 각주가 다른 글에서도 보이고 있네요.
정확히는 이 글 이후에 올라온 각주 없는 모든 글에서 보이고 있습니다.

간단하게 테스트를 해본 결과로는
1. 각주가 달린 글을 작성한다.
2. 그 이후에 쓰여지는 모든 글에 1의 각주가 보인다.
3. 각주가 달린 글을 또 작성한다.
4. 2에서 보이던 각주는 여전히 1의 각주로 보이고 3 이후로 쓰여진 글들에는 3의 각주가 보인다.
5. 3의 글을 지워도 여전히 새로 작성되는 글에는 3의 각주가 보인다.

**Comment by TintypeMolly** [comment]
일단은 footnote extension 떼버리겠음.

**Comment by TintypeMolly** [comment]
https://github.com/waylan/Python-Markdown 여기가 저장소인 것같다. fork떠서 함 보고 고쳐봐야겠다.
