### ISSUE TITLE
댓글을 달면 게시글의 수정시간이 변경된다

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#68]
제목 그대로 댓글을 달면 게시글이 수정된 것으로 간주됩니다. 의도한 사항이신지?

**Comment by TintypeMolly** [comment]
의도된 사항 아님. 고쳐야될듯. 댓글 갯수 수정때문에 onupdate가...걸리는건가

**Comment by TintypeMolly** [comment]
fixed 21e34ecd258e5b7eef7294d9ae79ac4ee098f24f
