### ISSUE TITLE
마크다운 링크가 깨짐.

### ISSUE THREAD

**Issue by angdev** [TintypeMolly/Yuzuki#70]
#65 변경사항과 관련이 있는 부분인가요?

https://poolc.org/article/view?id=196 에 보시면 깨져있네요.

원문

``` md
[여기](https://github.com/TintypeMolly/Yuzuki/issues)
```

렌더링 결과

``` html
<a href="a href=&quot;https://github.com/TintypeMolly/Yuzuki/issues&quot; rel=&quot;nofollow&quot; target=&quot;_blank&quot;&gt;https://github.com/TintypeMolly/Yuzuki/issues&lt;/a">여기</a>
```

**Comment by TintypeMolly** [comment]
오우...시바... 그런듯

**Comment by TintypeMolly** [comment]
엥 잠깐 저거 댓글이잖아. 뭐지?

**Comment by angdev** [comment]
@TintypeMolly ㄴㄴ @Elenesgu님이 링크를 댓글에 적은거예요.

**Comment by TintypeMolly** [comment]
@FeGs  아. 마크다운 링크가 저쪽으로 리다이렉트 된다는거군. 완전 문제파악 잘못했음. 음. 저걸로 해결 됐는지 다시 함 확인해봐야겠다.

**Comment by TintypeMolly** [comment]
@FeGs https://poolc.org/article/view?id=199 이유는 모르겠지만 해결. 니꺼 수정누른담에 다시 한번 확인 그대로 눌러봐라

**Comment by angdev** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ `compiled_content` 라는 놈에다 따로 저장하고 있군요. 미리 저장하면 좋긴 한데 이럴 때 업데이트를 해줘야하는건 안타깝네요.

**Comment by TintypeMolly** [comment]
fixed 44bea89e81ea7dc555500960456cd3a9da17e784
