### ISSUE TITLE
-자동로그인이 풀림.

### ISSUE THREAD

**Issue by saltedlion** [TintypeMolly/Yuzuki#72]
크롬 - PC에서 자동로그인 걸어놓고 모바일로 접속시 자동로그인 풀립니다.

**Comment by TintypeMolly** [comment]
... 장난하냐?

**Comment by Perlmint** [comment]
@TintypeMolly "장난하냐"라는 반응은 안좋다고 생각하는데 그냥 버그 아님이라고 하던가

**Comment by skyser2003** [comment]
아 이거 버그 아니었냐...  모바일에서 맨날 풀리길래 뭔가 했네

**Comment by TintypeMolly** [comment]
@Perlmint 내가 이딴 개소리 듣고 예의차릴 이유가 뭐임. 3G 안 되는 데에서 카톡 되게 해주세요 급인데.
@skyser2003 모바일에서 풀리는 건 아마 자동로그인 기한이 이틀이라 그런 거일 거임. 이거랑 전혀 다른 이슈.

**Comment by Perlmint** [comment]
@TintypeMolly 거기에 비유할 것은 아니라고 생각함.
이전 홈페이지의 동작은 설정한 모든 기기에서 다 되던 걸로 기억하는데
이게 같은 이름으로 되어 있으면서 동작이 다르다면 버그로 생각할 수 있다고 생각함

**Comment by saltedlion** [comment]
@TintypeMolly 자동로그인이라고 만들었는데 맨날 쳐풀려대는데 내가 씨발 이딴 욕까지 들어야하냐 걍 그럼 이틀 지나면 풀립니다라고 밑에 박아놓던가.
