### ISSUE TITLE
채팅방에서 채팅에 빈 메시지 날라감

### ISSUE THREAD

**Issue by scarlet9** [TintypeMolly/Yuzuki#73]
재현방법
1. Safari 8, OSX 10.10
2. 채팅방에서 그냥 엔터
3. 요 널 맨

원인
내장 validator가 음슴 인듯.

해결법
서버에서 유효성 검사해서 그냥 ignore하면 되지 않을까

**Comment by TintypeMolly** [comment]
수요일날 함 살펴보겠으

**Comment by Perlmint** [comment]
required 속성이 안먹음 js나 서버에서도 처리해줘야할 듯

**Comment by TintypeMolly** [comment]
#83 solved

**Comment by scarlet9** [comment]
ㅇㅋㅇㅋ

**Comment by TintypeMolly** [comment]
어 이거 내가 안닫았었나 ㅋㅋㅋㅋㅋ Close and Comment한 줄 알았는데 걍 코멘트만 했납네
