### ISSUE TITLE
채팅방 < 오류

### ISSUE THREAD

**Issue by todd032** [TintypeMolly/Yuzuki#74]
< 입력 후 영어 바로 붙여서 입력할 경우 텍스트 씹힘
eX) 

`<wdwdwdw`              => 빈칸으로 출력
`< wdwdwwdd`    =>    `< wdwdwdwdd` 출력

**Comment by TintypeMolly** [comment]
에에에 혼또니?

**Comment by Perlmint** [comment]
예시가 안보여서 수정함

**Comment by Perlmint** [comment]
github에서도 일어나네 ㅋㅋㅋㅋ

**Comment by Perlmint** [comment]
잘못 입력된 html tag로 인식되어서 bleach.clean 할 때 삭제됨.(정확히는 html5lib의 parser를 돌리는 과정에서 삭제됨)  
어차피 아무 태그도 허용 안할거라면 그냥 clean대신에 `<`와 `>`를 일괄 `&lt;`, `&gt;`로 치환하는 것은 어떨까?  
싶었는데 테스트 해보니 이상한 동작이 일어나네... 뭔가 방법을 찾아봐야할 듯
https://gist.github.com/Perlmint/8c33b068cee6c0326b08

**Comment by Perlmint** [comment]
이 버그 때문에 html을 채팅창에 입력할 수 있음...

**Comment by Perlmint** [comment]
`&lt;img src="//upload.namu.wiki/upload/uploadfile%2Fgm.jpg" http://goo.gl`

**Comment by TintypeMolly** [comment]
https://github.com/mozilla/bleach/issues/130

이거문제인듯

**Comment by Perlmint** [comment]
더 이상 채팅 기능을 사용하지 않으니 이 이슈는 닫는 것으로...
