### ISSUE TITLE
HTML entity를 사용해서 글 작성 후 수정에 들어가면 entity가 풀린채로 나옴

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#77]
md해석을 피하기 위해 `&#96;`를 입력했는데 <code>`</code>로 해석된 것으로 나옴

다시 저장시에 원본과 다르게 해석이 됨

**Comment by TintypeMolly** [comment]
solved https://github.com/TintypeMolly/Yuzuki/pull/78
