### ISSUE TITLE
사이트 어디서나 사용 가능한 미니 채팅방

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#85]
요구가 있는 것 같으니 일단 이슈로 남김.

사이트 어디서나 임베드 되어있는 미니 채팅방.

**Comment by TintypeMolly** [comment]
이거 @angdev 가 객체화를 많이 시켜놔서 코드 좀만 뜯어보면 크게 어렵지 않게 가능할거라는 생각만 든다만, 역시나 어디 박아야될지 잘 생각이 안난다. 페북마냥 오른쪽 아래에 빼꼼 박나

**Comment by Perlmint** [comment]
slack 사용하게 되었으니 필요없는 이슈가 되어서 닫음
