### ISSUE TITLE
새 글이 있을 경우 slack에 알림

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#89]
모든 게시판은 아니어도 공지라던가 몇개의 게시판은 slack으로 노티가 가면 좋을 것 같음

**Comment by Perlmint** [comment]
https://poolc.slack.com/services/14993908273 이것 참고하면 될 듯

**Comment by TintypeMolly** [comment]
added fde161aee69ec2c9300c57edd5a9930917e29428
