### ISSUE TITLE
page 미주 오류

### ISSUE THREAD

**Issue by Perlmint** [TintypeMolly/Yuzuki#96]
모든 page에서 `md_manual`에서 사용된 미주가 출력되고 있음.  

page를 생성할 때 초기화가 제대로 안되는 것 같음.

**Comment by Perlmint** [comment]
https://github.com/PoolC/Yuzuki/blob/master/resource/page.py#L25 여기 앞에서 md를 초기화 해줘야함

**Comment by TintypeMolly** [comment]
resloved 28aefe1ed8013e0f14fc25df00a4eead4ae3da96
